# Generated by Django 4.2.3 on 2023-08-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
